server:
  port: 9090
security:
    basic: 
      enabled: false
      
spring:
  autoconfigure:    exclude:      - org.springframework.cloud.aws.autoconfigure.messaging.MessagingAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
  security:
    oauth2:      client:        registration:          gateway:
            client-id: 5i0nveuj5547f40g077t5gj0e
            client-secret: 1pcku32d3ciel0oteruf9f1dveesc71ji3b1jjoaieiodnrskl2d
            scope: openid 
            redirect-uri: http://localhost:9090/login/oauth2/code/cognito
            client-name: awsuserpoolclient
            authorization-grant-type: authorization_code
            provider: cognito
        provider:
          cognito:
            authorization-uri: https://prasadgateway.auth.us-east-1.amazoncognito.com/oauth2/authorize
            issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_BK101UtqO
            jwk-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_BK101UtqO/.well-known/jwks.json
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: doctorservice
          uri: http://localhost:9091/
          predicates:
            - Path=/doctorservice/**
        - id: patientservice
          uri: http://localhost:9092/
          predicates:
            - Path=/patientservice/** 
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: DEBUG