server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: doctorservice
          uri: http://localhost:9091/
          predicates:
            - Path=/doctorservice/**
        - id: patientservice
          uri: http://localhost:9092/
          predicates:
            - Path=/patientservice/**