server:
  port:  9091
  servlet:
    context-path: /doctorservice

patient:
  restURL: http://localhost:9092/patientservice/patients

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_BK101UtqO
        
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO